server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_safe?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall

  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period: 2999ms

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    charset: UTF-8
    servlet:
      content-type: text/html
    cache: false

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 1024 # 连接池最大连接数(使用负值表示没有限制)
        max-wait: PT10S # 连接池最大阻塞等待时间(使用负值表示没有限制)10秒
        max-idle: 200 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: PT10S # 连接超时时间(10秒)

mybatis:
  mapper-locations: classpath:mappers/*.xml

swagger2:
  enable: true

pagehelper:
  helperDialect: mysql
  reasonable: true

logging:
  file: system.log
  path: classpath:logs
  level:
    com.yida.safe: debug

jwt:
  secretKey: 78944878877848fg)
  accessTokenExpireTime: PT2H
  refreshTokenExpireTime: PT8H
  refreshTokenExpireAppTime: P30D
  issuer: yida.com




